### ISSUE TITLE
Gif image not playing

### ISSUE THREAD

**Issue by samuraikid0** [balzack/databag#49] opened 2023-07-11 23:25 UTC
I've send a gif on sealed topic and it doesn't play can you check it out ?

Also I can't navigate throw the images of the sealed topic always reload the same image

**Comment by balzack** [comment] 2023-07-14 21:56
I am just testing your issue now, sorry for the delay.

I am able to reproduce your issue with gif not working on sealed topics, hopefully I will be able to resolve that soon.

I am not able to reproduce your issue of navigating through multiple images on a sealed message. I can tap on any of them, and the selected one loads first. I can also swipe on the loaded image and view the next or previous. Are you able to navigate images on non-sealed topics?

**Comment by samuraikid0** [comment] 2023-07-14 22:30
No, problem I notice now with what you asked that if I open an un-sealed topic and send picture
![Screenshot_20230714-232032_Databag](https://github.com/balzack/databag/assets/46766062/00e98f83-dd46-40e0-a976-db4efdf493ac)

The picture isn't send, I exit the un-sealed topic and open it again it shows

![Screenshot_20230714-232010_Databag_1](https://github.com/balzack/databag/assets/46766062/ea230f19-fbe2-4ef4-9b37-df8656d96bd2)

Thbaks !

**Comment by balzack** [comment] 2023-07-14 22:37
I see the 'invalid date' which must be a bug. 

Are you also saying that an image isn't getting sent? The app uploads the image in the background, so if you exit immediately, it might not have finished posting the image. You can switch topics while it uploads, but if you exit the app, the upload will not complete. There should be a green progress bar that appears when uploading.

**Comment by samuraikid0** [comment] 2023-07-14 22:50
Yes the screen stays blank after the bar finish, also happens if I send text.
 On the sealed topic works

**Comment by balzack** [comment] 2023-07-14 22:58
This seems like a serious bug, but I am having trouble reproducing. 

If you create a new topic with no members, then you post just text, will it show up?

**Comment by samuraikid0** [comment] 2023-07-14 22:58
https://github.com/balzack/databag/assets/46766062/e852ffe5-83f8-4701-9f76-7dc49868c94a

Let me know when you see to delete this video

**Comment by balzack** [comment] 2023-07-14 22:59
i just saw the video, you can delete, thx!

**Comment by balzack** [comment] 2023-07-14 23:05
It seems that the post is successful, but it's not synchronizing with the server. If you exit the app and then reload, does the data show up?

**Comment by samuraikid0** [comment] 2023-07-14 23:05
> This seems like a serious bug, but I am having trouble reproducing.
> 
> If you create a new topic with no members, then you post just text, will it show up?

Same invalid date host error


https://github.com/balzack/databag/assets/46766062/d826eee2-ac7a-4058-957f-63b8c2be1823

Warn me when you see it to edit

**Comment by balzack** [comment] 2023-07-14 23:06
I see this one also now, thank you.

**Comment by samuraikid0** [comment] 2023-07-14 23:13
> It seems that the post is successful, but it's not synchronizing with the server. If you exit the app and then reload, does the data show up?


Uploading 2023-07-15_00-10-16.mp4…

**Comment by samuraikid0** [comment] 2023-07-14 23:22
The message arrives on computer if I send 
mobile - computer but the topic seems to crash on mobile

**Comment by balzack** [comment] 2023-07-14 23:22
I see this one also if you want to delete.

**Comment by balzack** [comment] 2023-07-14 23:23
could you add me as a member to that topic? If I also get the same exception, then I would be able to capture it in the simulator.

**Comment by samuraikid0** [comment] 2023-07-14 23:26
Yes, send contact request

**Comment by balzack** [comment] 2023-07-14 23:33
I just requested the account I see.

**Comment by samuraikid0** [comment] 2023-07-14 23:34
Failed to Update Contact
Please try again

When requesting

**Comment by balzack** [comment] 2023-07-14 23:36
Hmm, it seems like the app is having trouble connecting to your server.

Can you try and connect to my account abeam@balzack.coredb.org?

**Comment by samuraikid0** [comment] 2023-07-14 23:38
The account doesn't seem to have any server attached

![Uploading IMG_20230715_003647.jpg…]()

**Comment by balzack** [comment] 2023-07-14 23:39
oops, yes...i was testing some use cases earlier in the week....is it fixed now?

**Comment by samuraikid0** [comment] 2023-07-14 23:40
Ive send an request

**Comment by balzack** [comment] 2023-07-14 23:40
ok, i think we are connected...

**Comment by balzack** [comment] 2023-07-15 04:49
If you get a chance, can you see if you have the same bug with unsealed topics on the demo server 'databag.coredb.org'?

**Comment by samuraikid0** [comment] 2023-07-15 16:46
Sorry didn't catch the last message
Yes I've got the same issue using 2 accounts on databag.coredb.org

**Comment by balzack** [comment] 2023-07-16 15:29
For some reason I am unable to even reproduce the title and date issue on a topic now. I saw in on my phone when we were testing last time. I will continue testing as I know there is an issue here, just letting you know it might be awhile for me to understand the issue.

**Comment by samuraikid0** [comment] 2023-07-16 18:22
No problem take your time the sealed topic work

It happens when I 
> Open unseal topic
> Send something
> Go back
> Enter the unsealed topic again

**Comment by samuraikid0** [comment] 2023-07-17 00:16
Here's the logcat during the topic creation if it helps
[logcat_07-17-2023_01-14-21.txt](https://github.com/balzack/databag/files/12065411/logcat_07-17-2023_01-14-21.txt)

**Comment by balzack** [comment] 2023-07-17 05:20
That is really helpful, any chance you can also get the logcat for when you send a message on the topic?

Thanks!!

**Comment by samuraikid0** [comment] 2023-07-17 14:34
Great ! 
I'll send you the logcat later

**Comment by samuraikid0** [comment] 2023-07-18 10:37
Here's the logcat 
[logcat1.txt](https://github.com/balzack/databag/files/12079468/logcat1.txt)

Thanks !

**Comment by balzack** [comment] 2023-07-18 15:39
This captured the error, so I should be able to fix it soon. Thank you!!!

**Comment by samuraikid0** [comment] 2023-07-21 14:58
Just updated the app and the topic creation  bug is fixed !
Thanks !

**Comment by balzack** [comment] 2023-07-21 15:08
such great news!!! I was really worried about this one as I could not reproduce it. thank you so much for the logs!!

**Comment by samuraikid0** [comment] 2023-07-21 15:26
The interest was mine and probably won't happen to others now
 Once the gif fix get's uploaded I'll close this issue, 
I'll leave it open to refer gif isn't working yet

Thanks  once again !

**Closed** 2023-07-27 23:42 UTC
